kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
name: no-privilege:no-privilege
rules:
- apiGroups:
- extensions
resources:
- podsecuritypolicies
resourceNames:
- psp
verbs:
- use
---
 
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
name: no-privilege:no-privilege
subjects:
- kind: Group
name: system:authenticated
apiGroup: rbac.authorization.k8s.io
roleRef:
kind: ClusterRole
name: no-privilege:no-privilege
apiGroup: rbac.authorization.k8s.io
